In [1]:
import numpy as np

l1 = [12, 23, 34, 45, 56]
l2 = [24, 35, 46, 57, 68]



In [2]:
l1+l2

[12, 23, 34, 45, 56, 24, 35, 46, 57, 68]

In [4]:
l3 = np.array([10, 20, 30])
l4 = np.array([40, 50, 60])
l3+l4

array([50, 70, 90])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.rand(3,2)

array([[0.92051713, 0.32811561],
       [0.25301257, 0.85278991],
       [0.7225633 , 0.10316994]])

In [15]:
np.random.randn(3,2)

array([[-0.41155554, -0.15100073],
       [-1.62387788,  0.42536202],
       [ 1.33327565, -0.09621319]])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])

In [17]:
print(arr.shape)

(2, 3)


In [18]:
print(arr.ndim)

2


In [19]:
print(arr.size)

6


In [20]:
print(arr.dtype)

int64


In [22]:
l5=np.array([1,2,3])
l6=np.array([4,5,6])

In [24]:
l5+l6

array([5, 7, 9])

In [25]:
l5*l6

array([ 4, 10, 18])

In [26]:
np.sin(l5)

array([0.84147098, 0.90929743, 0.14112001])

In [27]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [28]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [29]:
A@B

array([[19, 22],
       [43, 50]])

In [30]:
l7=np.array([1,2,3,4])

In [31]:
l7.sum()

np.int64(10)

In [32]:
l7.mean()

np.float64(2.5)

In [33]:
l7.max()

np.int64(4)

In [34]:
l7.min()

np.int64(1)

In [35]:
l7.std()

np.float64(1.118033988749895)

In [36]:
l8=np.array([1,2,3,4,5])

In [37]:
l8[0]

np.int64(1)

In [38]:
l8[1:4]

array([2, 3, 4])

In [39]:
l8[::2]

array([1, 3, 5])

In [40]:
l8[::-1]

array([5, 4, 3, 2, 1])

In [41]:
l9=np.array([[1,2,3],[4,5,6]])

In [42]:
l9[0,1]

np.int64(2)

In [43]:
l9[:,1]

array([2, 5])

In [44]:
l9[1,:2]

array([4, 5])

In [45]:
l10=np.array([1,2,3,4,5])
mask = l10 > 3
l10[mask]

array([4, 5])

In [46]:
arr1 = np.arange(6)
arr1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
a = np.array([1,2])
b = np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [64]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [62]:
a

array([1, 2])

In [63]:
b

array([3, 4])

In [49]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [50]:
a = np.array([1,2,3])

In [51]:
a+5

array([6, 7, 8])

In [67]:
np.save("array.npy", a)

In [66]:
loaded_arr = np.load('array.npy')